services:
  users-db:
    image: postgres:16
    environment:
      POSTGRES_DB: users        # Ensures 'users' DB is created
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - users-data:/var/lib/postgresql/data

  blogs-db:
    image: postgres:16
    environment:
      POSTGRES_DB: blogs        # Ensures 'blogs' DB is created
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - blogs-data:/var/lib/postgresql/data

volumes:
  users-data:
  blogs-data: